# Generated by Django 5.2.17 on 2026-09-28 05:34

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_child_due_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pumping",
            options={
                "default_permissions": ("view", "add", "change", "delete"),
                "ordering": ["-start"],
                "permissions": [
                    ("can_edit_pumping_settings", "Can edit Pumping settings")
                ],
                "verbose_name": "Pumping",
                "verbose_name_plural": "Pumping",
            },
        ),
        migrations.AddField(
            model_name="feeding",
            name="stash_amount",
            field=models.FloatField(
                blank=True,
                help_text="How much of what was drunk came from the milk stash.",
                null=True,
                verbose_name="Amount from stash",
            ),
        ),
        migrations.AddField(
            model_name="pumping",
            name="stash_amount",
            field=models.FloatField(
                blank=True,
                help_text="How much of this session went into the milk stash.",
                null=True,
                verbose_name="Amount stored",
            ),
        ),
        migrations.AlterField(
            model_name="pumping",
            name="child",
            field=models.ForeignKey(
                blank=True,
                help_text="Legacy: pumping belongs to a parent. Kept for older entries and apps.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pumping",
                to="core.child",
                verbose_name="Child",
            ),
        ),
        migrations.CreateModel(
            name="Parent",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=255, verbose_name="First name"),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Last name"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        editable=False,
                        max_length=100,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="parent/picture/",
                        verbose_name="Picture",
                    ),
                ),
                (
                    "children",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The children this parent's milk is for.",
                        related_name="parents",
                        to="core.child",
                        verbose_name="Children",
                    ),
                ),
            ],
            options={
                "verbose_name": "Parent",
                "verbose_name_plural": "Parents",
                "ordering": ["last_name", "first_name"],
                "default_permissions": ("view", "add", "change", "delete"),
            },
        ),
        migrations.AddField(
            model_name="feeding",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="The parent who breastfed. Only for the breast methods.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="breastfeedings",
                to="core.parent",
                verbose_name="Parent",
            ),
        ),
        migrations.AddField(
            model_name="pumping",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pumping",
                to="core.parent",
                verbose_name="Parent",
            ),
        ),
        migrations.CreateModel(
            name="StashAdjustment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(
                        default=django.utils.timezone.localtime, verbose_name="Time"
                    ),
                ),
                ("amount", models.FloatField(verbose_name="Amount")),
                (
                    "kind",
                    models.CharField(
                        choices=[("added", "Added"), ("discarded", "Discarded")],
                        max_length=20,
                        verbose_name="Kind",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Reason"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "feeding",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stash_adjustments",
                        to="core.feeding",
                        verbose_name="Feeding",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stash_adjustments",
                        to="core.parent",
                        verbose_name="Parent",
                    ),
                ),
                (
                    "tags",
                    core.models.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="core.Tagged",
                        to="core.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
            options={
                "verbose_name": "Stash adjustment",
                "verbose_name_plural": "Stash adjustments",
                "ordering": ["-time"],
                "default_permissions": ("view", "add", "change", "delete"),
            },
        ),
    ]
